### ISSUE TITLE
Asset transaction support

### ISSUE THREAD

**Issue by jumbojets** [KBryan/algorand_rust_sdk#2]
I am not sure if i was simply unable to locate it in the documentation, but does this sdk offer support for ASA (algorand asset) transactions?

**Comment by KBryan** [comment]
In Algorand the base asset is an ASA you can think of it as a utility token that is the foundation for creating any digital asset on the Algorand blockchain. So it assumes that anything you create/transact is at its foundation an ASA. If you are looking for a quick place to create your standard assets check out https://algodesk.io/#/portal/home . Then you can use any SDK to interface with your ASA. Hope this helps.

**Comment by jamesetaylor3** [comment]
Thanks for the reply! In my specific use case i am looking to transact USDC on algorand. In the official sdks i recall seeing a way to create specific asset transactions by supplying an asset id and giving. under the hood i believe this sets the transaction type to  "axfer" and "xaid" to the algorand asset id. However, the only transactions types i see [here](https://docs.rs/algo_rust_sdk/1.0.3/algo_rust_sdk/transaction/enum.TransactionType.html) are payment and key registration. am i missing something? i am pretty new to algorand so pardon me if i am.
